settings:
  username: "ada-zl125"
  commit_msg: "⚡ Update recent GitHub activity"
  max_lines: 3
  readme_file: "./README.md"
  url_text: "{REPO}{ID}"
  date:
    timezone: "Europe/London"
  commit_name: "github-actions[bot]"
  commit_email: "41898282+github-actions[bot]@users.noreply.github.com"
